// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: vesting/dex/genesis.proto

package types

import (
	fmt "fmt"
	_ "github.com/gogo/protobuf/gogoproto"
	proto "github.com/gogo/protobuf/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// GenesisState defines the dex module's genesis state.
type GenesisState struct {
	Params               Params            `protobuf:"bytes,1,opt,name=params,proto3" json:"params"`
	PortId               string            `protobuf:"bytes,2,opt,name=port_id,json=portId,proto3" json:"port_id,omitempty"`
	VestingList          []Vesting         `protobuf:"bytes,3,rep,name=vestingList,proto3" json:"vestingList"`
	VestingCount         uint64            `protobuf:"varint,4,opt,name=vestingCount,proto3" json:"vestingCount,omitempty"`
	SentVestingList      []SentVesting     `protobuf:"bytes,5,rep,name=sentVestingList,proto3" json:"sentVestingList"`
	SentVestingCount     uint64            `protobuf:"varint,6,opt,name=sentVestingCount,proto3" json:"sentVestingCount,omitempty"`
	TimedoutVestingList  []TimedoutVesting `protobuf:"bytes,7,rep,name=timedoutVestingList,proto3" json:"timedoutVestingList"`
	TimedoutVestingCount uint64            `protobuf:"varint,8,opt,name=timedoutVestingCount,proto3" json:"timedoutVestingCount,omitempty"`
}

func (m *GenesisState) Reset()         { *m = GenesisState{} }
func (m *GenesisState) String() string { return proto.CompactTextString(m) }
func (*GenesisState) ProtoMessage()    {}
func (*GenesisState) Descriptor() ([]byte, []int) {
	return fileDescriptor_0ac919355e3115ed, []int{0}
}
func (m *GenesisState) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *GenesisState) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_GenesisState.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *GenesisState) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GenesisState.Merge(m, src)
}
func (m *GenesisState) XXX_Size() int {
	return m.Size()
}
func (m *GenesisState) XXX_DiscardUnknown() {
	xxx_messageInfo_GenesisState.DiscardUnknown(m)
}

var xxx_messageInfo_GenesisState proto.InternalMessageInfo

func (m *GenesisState) GetParams() Params {
	if m != nil {
		return m.Params
	}
	return Params{}
}

func (m *GenesisState) GetPortId() string {
	if m != nil {
		return m.PortId
	}
	return ""
}

func (m *GenesisState) GetVestingList() []Vesting {
	if m != nil {
		return m.VestingList
	}
	return nil
}

func (m *GenesisState) GetVestingCount() uint64 {
	if m != nil {
		return m.VestingCount
	}
	return 0
}

func (m *GenesisState) GetSentVestingList() []SentVesting {
	if m != nil {
		return m.SentVestingList
	}
	return nil
}

func (m *GenesisState) GetSentVestingCount() uint64 {
	if m != nil {
		return m.SentVestingCount
	}
	return 0
}

func (m *GenesisState) GetTimedoutVestingList() []TimedoutVesting {
	if m != nil {
		return m.TimedoutVestingList
	}
	return nil
}

func (m *GenesisState) GetTimedoutVestingCount() uint64 {
	if m != nil {
		return m.TimedoutVestingCount
	}
	return 0
}

func init() {
	proto.RegisterType((*GenesisState)(nil), "vesting.dex.GenesisState")
}

func init() { proto.RegisterFile("vesting/dex/genesis.proto", fileDescriptor_0ac919355e3115ed) }

var fileDescriptor_0ac919355e3115ed = []byte{
	// 342 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x92, 0x2c, 0x4b, 0x2d, 0x2e,
	0xc9, 0xcc, 0x4b, 0xd7, 0x4f, 0x49, 0xad, 0xd0, 0x4f, 0x4f, 0xcd, 0x4b, 0x2d, 0xce, 0x2c, 0xd6,
	0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0xe2, 0x86, 0x4a, 0xe9, 0xa5, 0xa4, 0x56, 0x48, 0x89, 0xa4,
	0xe7, 0xa7, 0xe7, 0x83, 0xc5, 0xf5, 0x41, 0x2c, 0x88, 0x12, 0x29, 0x09, 0x64, 0xdd, 0x05, 0x89,
	0x45, 0x89, 0xb9, 0x50, 0xcd, 0x52, 0x28, 0xe6, 0xc2, 0x0c, 0x82, 0x48, 0xc9, 0x21, 0x4b, 0x15,
	0xa7, 0xe6, 0x95, 0xc4, 0xa3, 0xca, 0x2b, 0x21, 0xcb, 0x97, 0x64, 0xe6, 0xa6, 0xa6, 0xe4, 0x97,
	0xa2, 0xa9, 0x51, 0xda, 0xc3, 0xcc, 0xc5, 0xe3, 0x0e, 0x71, 0x6d, 0x70, 0x49, 0x62, 0x49, 0xaa,
	0x90, 0x21, 0x17, 0x1b, 0xc4, 0x7e, 0x09, 0x46, 0x05, 0x46, 0x0d, 0x6e, 0x23, 0x61, 0x3d, 0x24,
	0xd7, 0xeb, 0x05, 0x80, 0xa5, 0x9c, 0x58, 0x4e, 0xdc, 0x93, 0x67, 0x08, 0x82, 0x2a, 0x14, 0x12,
	0xe7, 0x62, 0x2f, 0xc8, 0x2f, 0x2a, 0x89, 0xcf, 0x4c, 0x91, 0x60, 0x52, 0x60, 0xd4, 0xe0, 0x0c,
	0x62, 0x03, 0x71, 0x3d, 0x53, 0x84, 0x6c, 0xb8, 0x60, 0x5e, 0xf7, 0xc9, 0x2c, 0x2e, 0x91, 0x60,
	0x56, 0x60, 0xd6, 0xe0, 0x36, 0x12, 0x41, 0x31, 0x30, 0x0c, 0xc2, 0x86, 0x9a, 0x88, 0xac, 0x5c,
	0x48, 0x89, 0x8b, 0x07, 0xca, 0x75, 0xce, 0x2f, 0xcd, 0x2b, 0x91, 0x60, 0x51, 0x60, 0xd4, 0x60,
	0x09, 0x42, 0x11, 0x13, 0xf2, 0xe0, 0xe2, 0x07, 0x79, 0x3c, 0x0c, 0xc9, 0x16, 0x56, 0xb0, 0x2d,
	0x12, 0x28, 0xb6, 0x04, 0x23, 0xd4, 0x40, 0x6d, 0x42, 0xd7, 0x26, 0xa4, 0xc5, 0x25, 0x80, 0x24,
	0x04, 0xb1, 0x91, 0x0d, 0x6c, 0x23, 0x86, 0xb8, 0x50, 0x08, 0x97, 0x30, 0x2c, 0x38, 0x91, 0x6d,
	0x66, 0x07, 0xdb, 0x2c, 0x83, 0x62, 0x73, 0x08, 0xaa, 0x3a, 0xa8, 0xed, 0xd8, 0xb4, 0x0b, 0x19,
	0x71, 0x89, 0xa0, 0x09, 0x43, 0x5c, 0xc1, 0x01, 0x76, 0x05, 0x56, 0x39, 0x27, 0xdd, 0x13, 0x8f,
	0xe4, 0x18, 0x2f, 0x3c, 0x92, 0x63, 0x7c, 0xf0, 0x48, 0x8e, 0x71, 0xc2, 0x63, 0x39, 0x86, 0x0b,
	0x8f, 0xe5, 0x18, 0x6e, 0x3c, 0x96, 0x63, 0x88, 0x12, 0x86, 0x45, 0x7e, 0x05, 0x24, 0xfa, 0x2b,
	0x0b, 0x52, 0x8b, 0x93, 0xd8, 0xc0, 0x91, 0x6e, 0x0c, 0x08, 0x00, 0x00, 0xff, 0xff, 0x1e, 0xe2,
	0x61, 0x59, 0xad, 0x02, 0x00, 0x00,
}

func (m *GenesisState) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *GenesisState) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *GenesisState) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.TimedoutVestingCount != 0 {
		i = encodeVarintGenesis(dAtA, i, uint64(m.TimedoutVestingCount))
		i--
		dAtA[i] = 0x40
	}
	if len(m.TimedoutVestingList) > 0 {
		for iNdEx := len(m.TimedoutVestingList) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.TimedoutVestingList[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintGenesis(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x3a
		}
	}
	if m.SentVestingCount != 0 {
		i = encodeVarintGenesis(dAtA, i, uint64(m.SentVestingCount))
		i--
		dAtA[i] = 0x30
	}
	if len(m.SentVestingList) > 0 {
		for iNdEx := len(m.SentVestingList) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.SentVestingList[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintGenesis(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x2a
		}
	}
	if m.VestingCount != 0 {
		i = encodeVarintGenesis(dAtA, i, uint64(m.VestingCount))
		i--
		dAtA[i] = 0x20
	}
	if len(m.VestingList) > 0 {
		for iNdEx := len(m.VestingList) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.VestingList[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintGenesis(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x1a
		}
	}
	if len(m.PortId) > 0 {
		i -= len(m.PortId)
		copy(dAtA[i:], m.PortId)
		i = encodeVarintGenesis(dAtA, i, uint64(len(m.PortId)))
		i--
		dAtA[i] = 0x12
	}
	{
		size, err := m.Params.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintGenesis(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func encodeVarintGenesis(dAtA []byte, offset int, v uint64) int {
	offset -= sovGenesis(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *GenesisState) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.Params.Size()
	n += 1 + l + sovGenesis(uint64(l))
	l = len(m.PortId)
	if l > 0 {
		n += 1 + l + sovGenesis(uint64(l))
	}
	if len(m.VestingList) > 0 {
		for _, e := range m.VestingList {
			l = e.Size()
			n += 1 + l + sovGenesis(uint64(l))
		}
	}
	if m.VestingCount != 0 {
		n += 1 + sovGenesis(uint64(m.VestingCount))
	}
	if len(m.SentVestingList) > 0 {
		for _, e := range m.SentVestingList {
			l = e.Size()
			n += 1 + l + sovGenesis(uint64(l))
		}
	}
	if m.SentVestingCount != 0 {
		n += 1 + sovGenesis(uint64(m.SentVestingCount))
	}
	if len(m.TimedoutVestingList) > 0 {
		for _, e := range m.TimedoutVestingList {
			l = e.Size()
			n += 1 + l + sovGenesis(uint64(l))
		}
	}
	if m.TimedoutVestingCount != 0 {
		n += 1 + sovGenesis(uint64(m.TimedoutVestingCount))
	}
	return n
}

func sovGenesis(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozGenesis(x uint64) (n int) {
	return sovGenesis(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *GenesisState) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowGenesis
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: GenesisState: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: GenesisState: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Params", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Params.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field PortId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.PortId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field VestingList", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.VestingList = append(m.VestingList, Vesting{})
			if err := m.VestingList[len(m.VestingList)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field VestingCount", wireType)
			}
			m.VestingCount = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.VestingCount |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field SentVestingList", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.SentVestingList = append(m.SentVestingList, SentVesting{})
			if err := m.SentVestingList[len(m.SentVestingList)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 6:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field SentVestingCount", wireType)
			}
			m.SentVestingCount = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.SentVestingCount |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 7:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field TimedoutVestingList", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.TimedoutVestingList = append(m.TimedoutVestingList, TimedoutVesting{})
			if err := m.TimedoutVestingList[len(m.TimedoutVestingList)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 8:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field TimedoutVestingCount", wireType)
			}
			m.TimedoutVestingCount = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.TimedoutVestingCount |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipGenesis(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthGenesis
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipGenesis(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowGenesis
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthGenesis
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupGenesis
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthGenesis
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthGenesis        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowGenesis          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupGenesis = fmt.Errorf("proto: unexpected end of group")
)
